import { Inter } from 'next/font/google';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { getDictionary } from './dictionaries'
import { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LangParams {
  lang: string;
}

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'ro' }];
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: LangParams;
}>) {
  const dict = await getDictionary(params.lang);

  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <Header t={params.lang} />
        <main>{children}</main>
        <Footer t={dict} />
      </body>
    </html>
  );
}
