import { Inter } from 'next/font/google';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { getDictionary } from './dictionaries'
import { Metadata } from 'next';
import './globals.css'
const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'ro' }];
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>
}>) {

  const { lang } = await params;
  const dict = await getDictionary(lang);
  return (
    <html lang={lang}>
      <body className={inter.className}>
        <Header t={dict} language={lang} />
        <main>{children}</main>
        <Footer t={dict} />
      </body>
    </html>
  );
}
