import { Inter } from 'next/font/google';
import Header from './components/Header';
import { getDictionary } from './[lang]/dictionaries'
import { Metadata } from 'next';
import './[lang]/globals.css'
const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode;

}>) {
  const lang = 'en';
  const dict = await getDictionary(lang);
  return (
    <html lang={lang}>
      <body className={inter.className}>
        <Header t={dict} language={lang} />
        <main>{children}</main>

      </body>
    </html>
  );
}
